name: Auto Create PR to Dev

on:
  push:
    branches:
      - front
      - back

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request with Random Reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const { repo, owner } = context.repo;
              const branchName = context.ref.split('/')[2];
              const pusher = context.actor;

              // Passo 1: Listar colaboradores com permissão de push (excluindo bots e o próprio autor)
              const collabsResponse = await github.rest.repos.listCollaborators({ owner, repo });
              const reviewers = collabsResponse.data
                .filter(user => user.permissions.push && user.login !== pusher && !user.login.includes('[bot]'));

              if (reviewers.length === 0) {
                console.log("Nenhum revisor disponível.");
                return;
              }

              // Passo 2: Sorteia 2 revisores
              const shuffled = reviewers.sort(() => 0.5 - Math.random());
              const selectedReviewers = shuffled.slice(0, 2).map(u => u.login);

              // Passo 3: Criar o Pull Request
              const result = await github.rest.pulls.create({
                owner,
                repo,
                title: `Merge changes from ${branchName} to dev`,
                head: branchName,
                base: 'dev',
                body: `Automated PR triggered by push to ${branchName}`,
              });

              const prNumber = result.data.number;

              // Passo 4: Solicitar revisão
              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: prNumber,
                reviewers: selectedReviewers
              });

              console.log(`PR criado: ${result.data.html_url}`);
              console.log(`Revisores: ${selectedReviewers.join(", ")}`);

            } catch (error) {
              console.error("Erro ao criar PR ou atribuir revisores:", error);
              throw error;
            }
