name: Criar Pull Request para Dev

on:
  push:
    branches:
      - front
      - back

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config user.name "Seu Nome"
          git config user.email "seu-email@example.com"
      
      - name: Criar um Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: ${{ github.ref_name }}  # Usando 'branch' ao invés de 'head'
          title: "Merge de ${GITHUB_REF} para dev"
          body: "PR automático gerado para o branch ${GITHUB_REF}."
