name: Create PR for dev

on:
  push:
    branches:
      - front
      - back

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config --global user.email "seu-email-no-github@exemplo.com"
        git config --global user.name "Seu Nome no GitHub"
        git remote set-url origin https://github.com/Maarzano/Prontus

    - name: Create Pull Request to dev
      run: |
        # Extrai o nome da branch do PR
        BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        
        # Checkout na branch dev
        git checkout dev
        
        # Puxa as últimas atualizações da dev
        git pull origin dev
        
        # Faz o merge da branch de origem (front ou back) para a dev
        git merge origin/$BRANCH_NAME
        
        # Empurra as mudanças para a dev
        git push origin dev

        # Cria o PR via GitHub CLI
        gh pr create --base dev --head $BRANCH_NAME --title "Automated PR for ${BRANCH_NAME}" --body "This PR was automatically created."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
