name: Create PR for dev

on:
  push:
    branches:
      - front
      - back

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Create Pull Request to dev
      run: |
        git config --global user.email "arthuramarzano10@gmail.com"
        git config --global user.name "Maarzano"
        git remote set-url origin https://github.com/${{ github.repository }}
        
        # Cria um PR para dev
        git checkout dev
        git pull origin dev
        git merge $GITHUB_REF
        git push origin dev
        
        # Faz o PR via GitHub CLI
        gh pr create --base dev --head $GITHUB_REF --title "Automated PR for ${GITHUB_REF}" --body "This PR was automatically created."

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
