name: Assign Reviewer

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Assign random reviewer
      run: |
        REVIEWS=("front-member1" "front-member2" "front-member3" "back-member1" "back-member2" "back-member3")
        REVIEWER=${REVIEWS[$RANDOM % ${#REVIEWS[@]}]}
        echo "Assigning $REVIEWER to the pull request."
        gh pr review --request $REVIEWER
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
